
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_BTN_SW_IP_DEVICE_ID,
		XPAR_BTN_SW_IP_BASEADDR,
		XPAR_BTN_SW_IP_INTERRUPT_PRESENT,
		XPAR_BTN_SW_IP_IS_DUAL
	},
	{
		XPAR_LEDS_DEVICE_ID,
		XPAR_LEDS_BASEADDR,
		XPAR_LEDS_INTERRUPT_PRESENT,
		XPAR_LEDS_IS_DUAL
	}
};


